version: '3.9'

services:
  store:
    volumes:
    - store_prod_data:/data
  reverse_proxy:
    volumes:
    - reverse_proxy_prod_data:/data
  server:
    build: server
    environment:
      PORT: "${FRONTEND_PORT?}"
  jaeger:
    volumes:
    - jaeger_prod_data:/badger

volumes:
  reverse_proxy_prod_data:
  store_prod_data:
  jaeger_prod_data: