version: '3.9'

services:
  api:
    command: ["/app/api"]
    build:
      context: ./backend
      args:
        CMD: api
    environment:
      PORT: "${API_PORT?}"
      DATA_STORE_URL: "${API_DATA_STORE_URL?}"
      BROKER_URL: "${API_BROKER_URL?}"
      QUEUE_URL: "${API_QUEUE_URL?}"
      SECRET: ${API_SECRET?}
      VERSION: "${API_VERSION?}"
      DATA_STORE_POOL_SIZE: "${API_DATA_STORE_POOL_SIZE?}"
      BROKER_POOL_SIZE: "${API_BROKER_POOL_SIZE?}"
      QUEUE_POOL_SIZE: "${API_QUEUE_POOL_SIZE?}"
      QUEUE_KEY: "${API_QUEUE_KEY?}"
      OTEL_AGENT_URL: "${OTEL_AGENT_URL?}"
  worker:
    command: ["/app/worker"]
    build:
      context: ./backend
      args:
        CMD: worker
    environment:
      QUEUE_KEY: "${API_QUEUE_KEY?}"
      QUEUE_URL: "${API_QUEUE_URL?}"
      QUEUE_POOL_SIZE: "${API_QUEUE_POOL_SIZE?}"
      DATA_STORE_URL: "${API_DATA_STORE_URL?}"
      DATA_STORE_POOL_SIZE: "${API_DATA_STORE_POOL_SIZE?}"
      OTEL_AGENT_URL: "${OTEL_AGENT_URL?}"
  store:
    build: ./redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${API_DATA_STORE_PASSWORD?}"]
  queue:
    build: ./redis
    command: ["redis-server", "--requirepass", "${API_QUEUE_PASSWORD?}"]
  broker:
    build: ./redis
    command: ["redis-server", "--requirepass", "${API_BROKER_PASSWORD?}"]
  reverse_proxy:
    build: ./reverse_proxy
    environment:
      DOMAIN: "${DOMAIN?}"
      FRONTEND_PORT: "${FRONTEND_PORT?}"
      API_PORT: "${API_PORT?}"
    ports:
    - 80:80
    - 443:443
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
    # https://github.com/jaegertracing/jaeger/issues/1543#issuecomment-495777421
    environment:
      BADGER_EPHEMERAL: 'false'
      SPAN_STORAGE_TYPE: badger
      BADGER_DIRECTORY_VALUE: /badger/data
      BADGER_DIRECTORY_KEY: /badger/key
  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - "${DEV_HOST_PATH?}/otel-collector-config.yml:/etc/otel-collector-config.yml"
  otel-agent:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-agent-config.yml"]
    volumes:
      - "${DEV_HOST_PATH?}/otel-agent-config.yml:/etc/otel-agent-config.yml"